version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: rnapp
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8000:80
    depends_on:
      - db
