spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/rnapp
        driver-class-name: org.postgresql.Driver
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect